apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-demo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Aakashgoyal89/platform-demo-gitops.git
    targetRevision: main
    path: platform-demo
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: platform-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

